function setdefaults()
%===============================================================================
% SETDEFAULTS
% Sets default figure property values for the root(0) object.
%
% MJR 10/2014
%===============================================================================

%Figure properties
set(0,'DefaultFigureColor', 'w');

%Axes properties
set(0,...
'DefaultAxesColor', 'w',...
'DefaultAxesFontName', 'Helvetica',...
'DefaultAxesFontSize',  18,...
'DefaultAxesLayer', 'Bottom',...
'DefaultAxesUnits', 'normalized',...
'DefaultAxesXcolor', [0 0 0], ...
'DefaultAxesYcolor', [0 0 0], ...
'DefaultAxesZcolor', [0 0 0],...
'DefaultAxesVisible', 'on',...
'DefaultAxesLineWidth',1.5);

set(0,...
'DefaultLineColor', 'b',...
'DefaultLineLineStyle', '-',...
'DefaultLineLineWidth', 1,...
'DefaultLineMarker', 'none',...
'DefaultLineMarkerSize', 8);

set(0,...
'DefaultTextColor', [0 0 0],...
'DefaultTextFontUnits', 'Points',...
'DefaultTextFontSize',  16,...
'DefaultTextFontName', 'Helvetica');



end